if(MSVC)
    option(gtest_force_shared_crt "" TRUE)
endif(MSVC)

if (APPLE)
    set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG TRUE)
endif(APPLE)

set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${CMAKE_BINARY_DIR}/arch" )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_BINARY_DIR}/lib" )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_BINARY_DIR}/bin" )

set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_BINARY_DIR}/arch" )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_BINARY_DIR}/lib" )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_BINARY_DIR}/bin" )

set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/arch" )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib" )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin" )

set( CMAKE_CXX_STANDARD 20 )

if( UNIX )
   set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -Wall -Wsign-compare -Werror")
   set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall -Wsign-compare -Werror")
endif( UNIX )

if( MSVC )
    set(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS}")
    set(CMAKE_C_FLAGS_RELEASE   "${CMAKE_C_FLAGS_RELEASE} /W4 /wd4267 /wd4244 /wd4100 /WX" )
    set(CMAKE_C_FLAGS_DEBUG     "${CMAKE_C_FLAGS_DEBUG} /W4 /wd4267 /wd4244 /wd4100 /WX")
    set(CMAKE_C_FLAGS           "${CMAKE_C_FLAGS} /W4 /wd4267 /wd4244 /wd4100 /WX" )
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /W4 /wd4267 /wd4244 /wd4100 /WX" )
    set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} /W4 /wd4267 /wd4244 /wd4100 /WX")
    set(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} /W4 /wd4267 /wd4244 /wd4100 /WX" )
endif( MSVC )

MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
        LIST(APPEND dirlist ${child})
    ENDIF()
   ENDFOREACH()
   SET(${result} ${dirlist})
ENDMACRO()

MACRO(CPPCHECK_TEST ProjectId ALL_SOURCE_FILES)
    if( UNIX )
        foreach (SOURCE_FILE ${ALL_SOURCE_FILES})
            string(FIND ${SOURCE_FILE} ${PROJECT_BINARY_DIR} PROJECT_TRDPARTY_DIR_FOUND)
            if (NOT ${PROJECT_TRDPARTY_DIR_FOUND} EQUAL -1)
                list(REMOVE_ITEM ALL_SOURCE_FILES ${SOURCE_FILE})
            endif ()
        endforeach ()
        if (NOT APPLE)
            find_program(CPPCHECK_EXEC /usr/bin/cppcheck)
            execute_process(COMMAND ${CPPCHECK_EXEC} --version OUTPUT_VARIABLE CPPCHECK_VERSION)
            if (CPPCHECK_VERSION)
                string(REGEX REPLACE "Cppcheck ([0-9]+\\.[0-9]+).*" "\\1" CPPCHECK_VERSION ${CPPCHECK_VERSION})
                if (CPPCHECK_VERSION VERSION_GREATER_EQUAL "2.11")
                    set(CPPCHECK_FLAGS "--enable=warning,performance,portability,information")
                    set(CPPCHECK_FLAGS "--disable=missingInclude")
                    set(CPPCHECK_FLAGS "--language=c++")
                    set(CPPCHECK_FLAGS "--std=c++11")
                    set(CPPCHECK_FLAGS "--error-exitcode=1")
                    set(CPPCHECK_FLAGS "--template=\"[{severity}][{id}] {message} {callstack} \\(On {file}:{line}\\)\"")
                    set(CPPCHECK_FLAGS "--verbose")
                    set(CPPCHECK_FLAGS "--quiet")
                else ()
                    set(CPPCHECK_FLAGS "--enable=warning,performance,portability,information")
                    set(CPPCHECK_FLAGS "--language=c++")
                    set(CPPCHECK_FLAGS "--std=c++11")
                    set(CPPCHECK_FLAGS "--error-exitcode=1")
                    set(CPPCHECK_FLAGS "--template=\"[{severity}][{id}] {message} {callstack} \\(On {file}:{line}\\)\"")
                    set(CPPCHECK_FLAGS "--verbose")
                    set(CPPCHECK_FLAGS "--quiet")
                endif ()
            endif ()
            add_custom_target(
                    "${ProjectId}_cppcheck" ALL
                    COMMAND ${CPPCHECK_EXEC} ${CPPCHECK_FLAGS} ${ALL_SOURCE_FILES}
            )
        ENDIF ()
    endif( UNIX )
ENDMACRO()